#!/usr/bin/env bash

set -euo pipefail

filter_non_local_ips() {
  local local_ipv4_regex='(192\.168|172\.(1[6-9]|2[0-9]|3[0-1])|127|10)\.'
  local local_ipv6_regex='(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))'
  grep -Ev "^($local_ipv4_regex|$local_ipv6_regex)"
}

extract_pcap() {
  local pcap_file="$1"
  # shellcheck disable=SC1003
  tshark \
    -r "$pcap_file" \
    -E separator=, \
    -T fields \
    -e ip.dst \
    -e ipv6.dst \
    -Y 'not (ipv6.dst == fe80::/10 and ipv6.src == fe80::/10) and not (ip.dst == 192.168.0.0/16 and ip.src == 192.168.0.0/16) and not (ip.dst == 10.0.0.0/8 and ip.src==10.0.0.0/8) and not (eth.dst[0] & 1)' |
    tr -d '\\' |
    tr ',' '\n' |
    grep . |
    filter_non_local_ips |
    sort -u
}

if [[ $# = 0 ]]; then
  filter_non_local_ips
elif [[ $# = 1 ]] && [[ "$1" == *.pcap ]]; then
  extract_pcap "$1"
else
  cmd="$(basename "$0")"
  echo "Usage examples:"
  echo "  cat ips.txt | $cmd"
  echo "  $cmd some_net_capture.pcap"
fi
